name: practise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  http: ^1.5.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  image: ^4.5.4

  # Camera & media
  image_picker: ^1.1.1
  camera: ^0.11.2+1
  permission_handler: ^12.0.1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/ToggleMenu.png
